removed unnecessary style declaration for the footer
AndreMendesMarcondes/gastoIffod pull request #3
Opened 2021-09-14 20:48 UTC by danillonogueira

Tinha uma tag <style> para estilizar o footer que não era necessária e estava jogando o footer para baixo. O footer do Bootstrap que você usou já joga o footer lá embaixo e deixa tudo redondinho. Se eu tiver comido bola, me dá um toque. Espero ter contribuído! :)

2021-09-15 14:38 UTC, AndreMendesMarcondes requested changes
![image](https://user-images.githubusercontent.com/26974157/133454199-b49a27f5-7a9f-4602-abeb-914bc8af40f2.png)
Danilo, quando é carregada a grid de orders por mês, se não tiver essa tag style, vai quebrar embaixo, como pode ver no print

2021-12-21 21:40 UTC, danillonogueira commented
> ![image](https://user-images.githubusercontent.com/26974157/133454199-b49a27f5-7a9f-4602-abeb-914bc8af40f2.png) Danilo, quando é carregada a grid de orders por mês, se não tiver essa tag style, vai quebrar embaixo, como pode ver no print

2021-12-21 21:41 UTC, danillonogueira commented
Resolvido!

2021-12-22 18:24 UTC, AndreMendesMarcondes approved these changes

2021-12-22 18:24 UTC, merged